# A good example can be found here:
# https://github.com/10up/action-wordpress-plugin-deploy/blob/develop/examples/deploy-on-publishing-a-new-release-and-attach-a-zip-file-to-the-release.yml

name: Deploy to WordPress.org

on:
  release:
    types: [released]

jobs:
  release:
    name: Deploy to WP.org
    runs-on: ubuntu-22.04
    environment: live
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install npm dependencies
        run: npm ci

      - name: Build assets for production
        run: npm run build

      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: videomail-for-ninja-forms

      # After the deploy, we also want to create a zip and upload it to the release on Github. We don't want
      # users to have to go to the repository to find our plugin :).
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          files: ${{github.workspace}}/videomail-for-ninja-forms.zip
