name: Deploy to WordPress.org

on:
  release:
    types: [released]

jobs:
  release:
    name: New release
    runs-on: ubuntu-20.04
    environment: live
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install composer dependencies
        uses: php-actions/composer@v5
        with:
          php_version: 7.4
          dev: no

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install npm dependencies
        run: |
          npm install -g npm@9
          npm ci

      - name: Build assets for production
        run: npm run build

      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: videomail-for-ninja-forms

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{github.workspace}}/videomail-for-ninja-forms.zip
          asset_name: videomail-for-ninja-forms.zip
          asset_content_type: application/zip
