name: Deploy to WordPress.org

on:
  release:
    types: [released]

jobs:
  release:
    name: New release
    runs-on: ubuntu-22.04
    environment: live
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm dependencies
        run: npm ci

      - name: Build assets for production
        run: npm run build

      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: videomail-for-ninja-forms

      - name: Upload release asset
        # TODO Switch to another action as this one is deprecated. Maybe softprops/action-gh-release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{github.workspace}}/videomail-for-ninja-forms.zip
          asset_name: videomail-for-ninja-forms.zip
          asset_content_type: application/zip
